### ISSUE TITLE
bug: hub_peering_use_remote_gateways should not try to enable use_remote_gateways for both the spoke and the hub network with a single setting

### ISSUE THREAD

**Issue by valsharess** [Azure/terraform-azurerm-lz-vending#334]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.7.2
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.12.0
+ provider registry.terraform.io/carlpett/sops v0.7.2
+ provider registry.terraform.io/hashicorp/azurerm v3.91.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
```

Please enter the module version that you are using:

```text
4.0.0
```

### Description

A common scenario is to not have a remote gateway in the spoke network so this fails when set as it is trying to enable 'use_remote_gateways' on both vnets instead of just on the spoke network. 

#### Steps to Reproduce

1. Define a vnet using the lz vending module and have hub_peering_use_remote_gateways = true
2. Terraform fails as the vnet does not have a remote gateway, the peer does however so it half works
#### Additional context
```
  virtual_networks = {
    vnet1 = {
      name                            = "connectivity-spoke"
      address_space                   = ["10.193.4.0/24"]
      resource_group_name             = "rg-networking"
      hub_peering_enabled             = true
      hub_network_resource_id         = var.hub_networks_by_location["australiaeast"].id
     # there is only a remote gateway in the hub, this will fail as it tries to enable it for not only the hub vnet but this vnet(connectivity-spoke)
      hub_peering_use_remote_gateways = true
    }
  }
```

`│ Error: creating/updating PUT https://management.azure.com/subscriptions/****/resourceGroups/****-australiaeast/providers/Microsoft.Network/virtualNetworks/****-hub-australiaeast/virtualNetworkPeerings/peer-****
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: RemoteVnetHasNoGateways
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "RemoteVnetHasNoGateways",
│     "message": "Peering /subscriptions/***** cannot have UseRemoteGateway flag set to true because remote virtual network /subscriptions/*****/resourceGroups/rg-networking/providers/Microsoft.Network/virtualNetworks/connectivity-spoke referenced by the peering does not have any gateways.",
│     "details": []
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with module.landing_zones.module.Integrations.module.virtualnetwork[0].azapi_resource.peering_hub_inbound["vnet1"],
│   on .terraform/modules/landing_zones.Integrations/modules/virtualnetwork/main.tf line 120, in resource "azapi_resource" "peering_hub_inbound":
│  120: resource "azapi_resource" "peering_hub_inbound" {`

**Comment by knuterik-ballestad** [comment]
We are experiencing the same on 4.0.1

**Comment by matt-FFFFFF** [comment]
Hi, looking at this it does seem to be incorrect. Thanks for reporting.

**Comment by knuterik-ballestad** [comment]
Well, if I upgrade from 3.4.2 to 4.0.1, I get this error message:

`RESPONSE 400: 400 Bad Request
│ ERROR CODE: RemoteVnetHasNoGateways
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "RemoteVnetHasNoGateways",
│     "message": "Peering /subscriptions/7224853d-5936-423e-bdfd-eab3195aa374/resourceGroups/rg-vnet-hub-prod-001/providers/Microsoft.Network/virtualNetworks/ALZ-Connectivity-vnet-prod-hub-norwayeast-001/virtualNetworkPeerings/peer-36cd8786-ca5f-5e0b-a814-8762[30](https://github.com/skagerak-energi/alz-vending/actions/runs/7902892882/job/21602824475#step:8:31)424011 cannot have UseRemoteGateway flag set to true because remote virtual network /subscriptions/8466477b-c037-49fa-9034-4fd161ab19de/resourceGroups/rg-nettverk/providers/Microsoft.Network/virtualNetworks/vnet-ene-d-ena-testlx-9 referenced by the peering does not have any gateways.",
│     "details": []
│   }
│ }`

If I revert to v 3.4.2, the error disappears...

**Comment by matt-FFFFFF** [comment]
This is due to the feature introduced whereby we can control the peering direction from: both, inbound, outbound.

There was an error that I will fix today!
