### ISSUE TITLE
feat: budget support

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-lz-vending#64]
- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

Add capability to deploy budgets with subscriptions

**Comment by nyanhp** [comment]
Hey @matt-FFFFFF, I'd be happy to contribute since we are running into just this issue at my org. Assigning the Deploy-Budget policy overall is a perfectly serviceable solution, but having the ability to define a budget per subscription would be nice to have for our subscription owners in management groups without an enforced budget.

What I am unsure about is the extent to which this should be implemented. My idea would be to incorporate everything (<https://learn.microsoft.com/en-us/azure/templates/microsoft.consumption/2021-10-01/budgets?pivots=deployment-language-terraform#resource-format-2>) **except** for the filters. This would be added to the subscription module and be deployed using the AzApi provider.

**Comment by matt-FFFFFF** [comment]
Hi @nyanhp 

This sounds a sensible approach. Happy for you to take this on and thank you for offering to do so!
