### ISSUE TITLE
subscription_alias_enabled = false doesn't allow creation of subscription

### ISSUE THREAD

**Issue by danielmarker** [Azure/terraform-azurerm-lz-vending#77]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**:

**azure provider**:

**module**:

#### Describe the bug

When deciding not to use aliases using ```subscription_alias_enabled = false``` - new subscriptions are not created.

#### Steps to Reproduce

subscription_alias_enabled = false
Add relevant subscription details
terraform apply

**Comment by matt-FFFFFF** [comment]
Hi @danielmarker, thanks for the issue

This is by design, the subscription alias resource is the recommended way of creating subscriptions: https://docs.microsoft.com/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=rest

This is used by the AzureRM provider's [`azurerm_subscription`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription) resource
